on:
  repository_dispatch:
    types: do_something
    branches:
        - MuskanPaliwal-patch-1
jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Repository Profiler
        uses: Alokit-Innovations/repo-profiler@v0
