on:
  repository_dispatch:
    types: do_something
    # branches:
    #   - mkp/trigger_github_action
jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.ref }}
      - name: Repository Profiler
        uses: Alokit-Innovations/repo-profiler@v0
